require './test_helper'
start_simple_cov("suite")

ENV['ORO_LOGLEVEL'] = '3'
require './test_base'
require './test_corba'
require './test_orocos'
require './test_process'
require './test_properties'
require './test_task'
require './test_ports'
require './test_operations'
require './test_nameservice'
require './test_nameservice_deprecated'
require './test_async_task'
require './test_async_ports'
require './test_async_task_proxy'
require './test_async_name_service'
