ENV['ORO_LOGLEVEL'] = '3'
require 'test_base'
require 'test_corba'
require 'test_orocos'
require 'test_process'
require 'test_properties'
require 'test_task'
require 'test_ports'

# require 'test_commands'
# require 'test_methods'
